services:
  - type: web
    name: laravel-vite-app
    env: php
    rootDir: .
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      cp .env.example .env
      php artisan key:generate
      npm install
      npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan migrate --force || true
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/data/database.sqlite
