services:
  - type: web
    name: laravel-vite-app
    env: php
    rootDir: .
    buildCommand: |
      # Cài Composer packages
      composer install --optimize-autoloader --no-dev

      # Tạo file .env nếu chưa có
      cp .env.example .env || true

      # Tạo key ứng dụng
      php artisan key:generate

      # Cài Node packages và build React qua Vite
      npm install
      npm run build

      # Cache cấu hình Laravel
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache

      # Tùy chọn: migrate DB nếu bạn có database
      php artisan migrate --force || true
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/data/database.sqlite
